"""
Executive Scouting Report Exporter Implementation
"""

import os
from typing import Dict, Any
from scoutedge.models import AthleteProfile, EvaluationResult


class ScoutReportExporter:
    """
    ScoutReportExporter

    Converts ScoutEdge intelligence evaluation results into formatted Markdown dossiers,
    rich responsive HTML executive reports, and plain text executive summaries.
    """

    def export_markdown(self, profile: AthleteProfile, eval_result: EvaluationResult) -> str:
        """Generates a structured GitHub-Flavored Markdown Scouting Dossier."""
        md = f"""# SCOUTEDGE EXECUTIVE SCOUTING DOSSIER

**Generated:** {eval_result.timestamp}  
**Athlete ID:** `{profile.athlete_id}`  

---

## 👤 Athlete Metadata

| Attribute | Value |
| :--- | :--- |
| **Name** | **{profile.name}** |
| **Sport / Position** | {profile.sport} — {profile.primary_position} |
| **Current Team** | {profile.current_team} |
| **Competition Tier** | {profile.league_tier} |
| **Physical Profile** | {profile.height_cm} cm / {profile.weight_kg} kg |
| **Birth Date** | {profile.birth_date} |

---

## 📊 ScoutEdge Intelligence Signals

### 1. SE-R™ Performance Rating
- **Overall SE-R™ Rating:** **`{eval_result.se_r.overall_rating} / 100`**
- **Percentile Rank:** `{eval_result.se_r.percentile_rank}%`
- **Sub-Ratings:** Technical `{eval_result.se_r.technical_rating}` | Tactical `{eval_result.se_r.tactical_rating}` | Physical `{eval_result.se_r.physical_rating}`
- **Key Drivers:** {", ".join(eval_result.se_r.key_drivers)}

### 2. PGI™ Player Growth Index
- **PGI™ Growth Score:** **`{eval_result.pgi.pgi_score} / 100`**
- **Development Stage:** `{eval_result.pgi.development_stage}`
- **Growth Ceiling Projection:** `{eval_result.pgi.growth_ceiling_projection} / 100`
- **Progression Velocity:** `{eval_result.pgi.progression_velocity}`

### 3. EdgeCare™ Workload & Readiness
- **Readiness Index:** **`{eval_result.edgecare.readiness_index} / 100`**
- **ACWR Ratio:** `{eval_result.edgecare.acwr_ratio}`
- **Injury Risk Classification:** `{eval_result.edgecare.injury_risk_category}`
- **Recommended Match Minutes:** `{eval_result.edgecare.recommended_minutes} mins`

---

## 🎯 Decision Intelligence Summary

- **Overall Fit Score:** **`{eval_result.fit_score} / 100`**
- **Final Executive Recommendation:** **`{eval_result.recommendation.upper()}`**

### Explainability Evidence Reasons
"""
        for reason in eval_result.explainability_reasons:
            md += f"- ✓ {reason}\n"

        md += f"""
---

## 📄 Verified Live Resume™ Summary
> {eval_result.live_resume.career_trajectory_summary}

---
*Report generated by EdgeSphere Sports Intelligence Private Limited — ScoutEdge System v0.1.0*
"""
        return md.strip()

    def export_html(self, profile: AthleteProfile, eval_result: EvaluationResult) -> str:
        """Generates a self-contained, responsive HTML Executive Scouting Report."""
        reasons_html = "".join([f"<li>✓ {r}</li>" for r in eval_result.explainability_reasons])
        drivers_html = ", ".join(eval_result.se_r.key_drivers)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ScoutEdge Dossier — {profile.name}</title>
    <style>
        :root {{
            --bg-color: #0f172a;
            --card-bg: #1e293b;
            --accent-blue: #38bdf8;
            --accent-green: #22c55e;
            --accent-amber: #f59e0b;
            --text-main: #f8fafc;
            --text-muted: #94a3b8;
            --border-color: #334155;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: var(--bg-color);
            color: var(--text-main);
            margin: 0;
            padding: 24px;
        }}
        .container {{
            max-width: 850px;
            margin: 0 auto;
        }}
        .header {{
            border-bottom: 2px solid var(--border-color);
            padding-bottom: 16px;
            margin-bottom: 24px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}
        .brand {{
            font-size: 24px;
            font-weight: 800;
            letter-spacing: -0.5px;
            color: var(--accent-blue);
        }}
        .badge {{
            background: rgba(56, 189, 248, 0.15);
            color: var(--accent-blue);
            padding: 6px 14px;
            border-radius: 20px;
            font-size: 13px;
            font-weight: 600;
        }}
        .grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
            gap: 16px;
            margin-bottom: 24px;
        }}
        .card {{
            background: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 12px;
            padding: 20px;
        }}
        .card h3 {{
            margin-top: 0;
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            color: var(--text-muted);
        }}
        .score {{
            font-size: 36px;
            font-weight: 800;
            color: var(--text-main);
            margin: 8px 0;
        }}
        .bar-bg {{
            background: #334155;
            height: 8px;
            border-radius: 4px;
            overflow: hidden;
            margin-top: 8px;
        }}
        .bar-fill {{
            background: var(--accent-blue);
            height: 100%;
        }}
        .recommendation-box {{
            background: linear-gradient(135deg, rgba(34, 197, 94, 0.15), rgba(56, 189, 248, 0.15));
            border: 1px solid var(--accent-green);
            border-radius: 12px;
            padding: 24px;
            margin-bottom: 24px;
            text-align: center;
        }}
        .recommendation-title {{
            font-size: 28px;
            font-weight: 900;
            color: var(--accent-green);
            letter-spacing: 1px;
        }}
        ul {{
            padding-left: 20px;
            color: var(--text-muted);
        }}
        li {{
            margin-bottom: 6px;
        }}
        .footer {{
            text-align: center;
            font-size: 12px;
            color: var(--text-muted);
            margin-top: 32px;
            border-top: 1px solid var(--border-color);
            padding-top: 16px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div>
                <div class="brand">SCOUTEDGE Live™</div>
                <div style="color: var(--text-muted); font-size: 14px;">Executive Talent Evaluation Dossier</div>
            </div>
            <div class="badge">{eval_result.timestamp[:10]}</div>
        </div>

        <div class="card" style="margin-bottom: 24px;">
            <h2 style="margin: 0 0 8px 0; font-size: 22px;">{profile.name}</h2>
            <div style="color: var(--text-muted); font-size: 14px;">
                {profile.primary_position} • {profile.current_team} ({profile.league_tier}) • {profile.height_cm} cm, {profile.weight_kg} kg
            </div>
        </div>

        <div class="recommendation-box">
            <div style="font-size: 12px; text-transform: uppercase; color: var(--text-muted); letter-spacing: 1px;">Executive Decision</div>
            <div class="recommendation-title">{eval_result.recommendation.upper()}</div>
            <div style="margin-top: 6px; font-weight: 600; color: var(--text-main);">Overall Fit Score: {eval_result.fit_score} / 100</div>
        </div>

        <div class="grid">
            <div class="card">
                <h3>SE-R™ Performance Rating</h3>
                <div class="score">{eval_result.se_r.overall_rating}</div>
                <div style="font-size: 13px; color: var(--text-muted);">Percentile: {eval_result.se_r.percentile_rank}%</div>
                <div class="bar-bg"><div class="bar-fill" style="width: {eval_result.se_r.overall_rating}%;"></div></div>
                <div style="font-size: 12px; color: var(--text-muted); margin-top: 10px;">Drivers: {drivers_html}</div>
            </div>

            <div class="card">
                <h3>PGI™ Player Growth Index</h3>
                <div class="score">{eval_result.pgi.pgi_score}</div>
                <div style="font-size: 13px; color: var(--text-muted);">Stage: {eval_result.pgi.development_stage}</div>
                <div class="bar-bg"><div class="bar-fill" style="width: {eval_result.pgi.pgi_score}%; background: var(--accent-amber);"></div></div>
                <div style="font-size: 12px; color: var(--text-muted); margin-top: 10px;">Ceiling Projection: {eval_result.pgi.growth_ceiling_projection}</div>
            </div>

            <div class="card">
                <h3>EdgeCare™ Readiness Index</h3>
                <div class="score">{eval_result.edgecare.readiness_index}</div>
                <div style="font-size: 13px; color: var(--text-muted);">ACWR: {eval_result.edgecare.acwr_ratio} | Risk: {eval_result.edgecare.injury_risk_category}</div>
                <div class="bar-bg"><div class="bar-fill" style="width: {eval_result.edgecare.readiness_index}%; background: var(--accent-green);"></div></div>
                <div style="font-size: 12px; color: var(--text-muted); margin-top: 10px;">Recommended: {eval_result.edgecare.recommended_minutes} mins</div>
            </div>
        </div>

        <div class="card">
            <h3>Explainability Evidence Reasons</h3>
            <ul>
                {reasons_html}
            </ul>
        </div>

        <div class="footer">
            EdgeSphere Sports Intelligence Private Limited • ScoutEdge Intelligence System
        </div>
    </div>
</body>
</html>"""
        return html.strip()

    def export_summary_text(self, profile: AthleteProfile, eval_result: EvaluationResult) -> str:
        """Generates plain text executive summary."""
        txt = (
            f"SCOUTEDGE REPORT: {profile.name} ({profile.primary_position}, {profile.current_team})\n"
            f"SE-R Rating: {eval_result.se_r.overall_rating} (Percentile: {eval_result.se_r.percentile_rank}%)\n"
            f"PGI Growth Score: {eval_result.pgi.pgi_score} ({eval_result.pgi.development_stage})\n"
            f"EdgeCare Readiness: {eval_result.edgecare.readiness_index} (Risk: {eval_result.edgecare.injury_risk_category})\n"
            f"Fit Score: {eval_result.fit_score}/100\n"
            f"RECOMMENDATION: {eval_result.recommendation.upper()}\n"
            f"Key Reasons: {', '.join(eval_result.explainability_reasons)}"
        )
        return txt
